# Copyright (C) 2023 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/R11s/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/oppo/R11s/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/oppo/R11s/proprietary/etc/camera/ashdr/ncf_pack.ncf:system/etc/camera/ashdr/ncf_pack.ncf \
    vendor/oppo/R11s/proprietary/etc/camera/cp/CPCalibrationData.bin:system/etc/camera/cp/CPCalibrationData.bin \
    vendor/oppo/R11s/proprietary/etc/camera/cp/FusionCalibrationParams.bin:system/etc/camera/cp/FusionCalibrationParams.bin \
    vendor/oppo/R11s/proprietary/etc/camera/cp/SystemParamsBokeh.bin:system/etc/camera/cp/SystemParamsBokeh.bin \
    vendor/oppo/R11s/proprietary/etc/camera/cp/SystemParamsFusion.bin:system/etc/camera/cp/SystemParamsFusion.bin \
    vendor/oppo/R11s/proprietary/etc/camera/faceTpl0.rgb32:system/etc/camera/faceTpl0.rgb32 \
    vendor/oppo/R11s/proprietary/etc/camera/faceTpl1.rgb32:system/etc/camera/faceTpl1.rgb32 \
    vendor/oppo/R11s/proprietary/etc/camera/gasryuv.model:system/etc/camera/gasryuv.model \
    vendor/oppo/R11s/proprietary/etc/camera/skinSeg.model:system/etc/camera/skinSeg.model \
    vendor/oppo/R11s/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_10_0.fw:system/etc/firmware/cpp_firmware_v1_10_0.fw \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_12_0.fw:system/etc/firmware/cpp_firmware_v1_12_0.fw \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_5_0.fw:system/etc/firmware/cpp_firmware_v1_5_0.fw \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_5_1.fw:system/etc/firmware/cpp_firmware_v1_5_1.fw \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_5_2.fw:system/etc/firmware/cpp_firmware_v1_5_2.fw \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw \
    vendor/oppo/R11s/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:system/etc/firmware/cpp_firmware_v1_8_0.fw \
    vendor/oppo/R11s/proprietary/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/oppo/R11s/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/oppo/R11s/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/oppo/R11s/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/oppo/R11s/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/oppo/R11s/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/oppo/R11s/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/oppo/R11s/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/oppo/R11s/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/GyroOffset_db.config:system/etc/vstab_configs/GyroOffset_db.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/fsync_db.config:system/etc/vstab_configs/fsync_db.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_preview.config:system/etc/vstab_configs/vstab_db_1080p_preview.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_preview_0_imx519_bmi.config:system/etc/vstab_configs/vstab_db_1080p_preview_0_imx519_bmi.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_preview_0_imx519_lsm.config:system/etc/vstab_configs/vstab_db_1080p_preview_0_imx519_lsm.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_0.config:system/etc/vstab_configs/vstab_db_1080p_video_0.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_imx519_bmi.config:system/etc/vstab_configs/vstab_db_1080p_video_0_imx519_bmi.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_imx519_lsm.config:system/etc/vstab_configs/vstab_db_1080p_video_0_imx519_lsm.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq.config:system/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov.config:system/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov_bmi.config:system/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov_bmi.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov_main.config:system/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov_main.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_sfov.config:system/etc/vstab_configs/vstab_db_1080p_video_0_sfov.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_sfov_lsm.config:system/etc/vstab_configs/vstab_db_1080p_video_0_sfov_lsm.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_sfov_main.config:system/etc/vstab_configs/vstab_db_1080p_video_0_sfov_main.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1080p_video_1.config:system/etc/vstab_configs/vstab_db_1080p_video_1.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1350p_video_0.config:system/etc/vstab_configs/vstab_db_1350p_video_0.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_1350p_video_0_s5k2p7sq.config:system/etc/vstab_configs/vstab_db_1350p_video_0_s5k2p7sq.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_4k_preview.config:system/etc/vstab_configs/vstab_db_4k_preview.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_4k_video_0.config:system/etc/vstab_configs/vstab_db_4k_video_0.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_4k_video_1.config:system/etc/vstab_configs/vstab_db_4k_video_1.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_preview.config:system/etc/vstab_configs/vstab_db_720p_preview.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_preview_0_imx519_bmi.config:system/etc/vstab_configs/vstab_db_720p_preview_0_imx519_bmi.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_preview_0_imx519_lsm.config:system/etc/vstab_configs/vstab_db_720p_preview_0_imx519_lsm.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_0.config:system/etc/vstab_configs/vstab_db_720p_video_0.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_0_imx519_bmi.config:system/etc/vstab_configs/vstab_db_720p_video_0_imx519_bmi.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_0_imx519_lsm.config:system/etc/vstab_configs/vstab_db_720p_video_0_imx519_lsm.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq.config:system/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov.config:system/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov_bmi.config:system/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov_bmi.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov_main.config:system/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov_main.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_0_sfov.config:system/etc/vstab_configs/vstab_db_720p_video_0_sfov.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_0_sfov_lsm.config:system/etc/vstab_configs/vstab_db_720p_video_0_sfov_lsm.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_0_sfov_main.config:system/etc/vstab_configs/vstab_db_720p_video_0_sfov_main.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_720p_video_1.config:system/etc/vstab_configs/vstab_db_720p_video_1.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_900p_video_0.config:system/etc/vstab_configs/vstab_db_900p_video_0.config \
    vendor/oppo/R11s/proprietary/etc/vstab_configs/vstab_db_900p_video_0_s5k2p7sq.config:system/etc/vstab_configs/vstab_db_900p_video_0_s5k2p7sq.config \
    vendor/oppo/R11s/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/oppo/R11s/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/oppo/R11s/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/oppo/R11s/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/oppo/R11s/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/oppo/R11s/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/oppo/R11s/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar \
    vendor/oppo/R11s/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/oppo/R11s/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/oppo/R11s/proprietary/lib/com.quicinc.cne.server@1.0.so:system/lib/com.quicinc.cne.server@1.0.so \
    vendor/oppo/R11s/proprietary/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/oppo/R11s/proprietary/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/oppo/R11s/proprietary/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/oppo/R11s/proprietary/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/oppo/R11s/proprietary/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
    vendor/oppo/R11s/proprietary/lib/vendor.qti.latency@2.0.so:system/lib/vendor.qti.latency@2.0.so \
    vendor/oppo/R11s/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/oppo/R11s/proprietary/lib64/com.quicinc.cne.server@1.0.so:system/lib64/com.quicinc.cne.server@1.0.so \
    vendor/oppo/R11s/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/oppo/R11s/proprietary/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/oppo/R11s/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/oppo/R11s/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/oppo/R11s/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/oppo/R11s/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/oppo/R11s/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/oppo/R11s/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/oppo/R11s/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/oppo/R11s/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/oppo/R11s/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/oppo/R11s/proprietary/lib64/libmmrtpdecoder.so:system/lib64/libmmrtpdecoder.so \
    vendor/oppo/R11s/proprietary/lib64/libmmrtpencoder.so:system/lib64/libmmrtpencoder.so \
    vendor/oppo/R11s/proprietary/lib64/librcc.so:system/lib64/librcc.so \
    vendor/oppo/R11s/proprietary/lib64/vendor.qti.hardware.data.latency@1.0.so:system/lib64/vendor.qti.hardware.data.latency@1.0.so \
    vendor/oppo/R11s/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so \
    vendor/oppo/R11s/proprietary/lib64/vendor.qti.latency@2.0.so:system/lib64/vendor.qti.latency@2.0.so

PRODUCT_PACKAGES += \
    QtiTelephonyService \
    CNEService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel
